### ISSUE TITLE
666

### ISSUE THREAD

**Issue by mynameisliang** [moyuyc/paint_online#1]
博主你好，这个白板的功能很细致，可见你对h5和nodejs非常熟练，我这里遇到了一个问题，就是在实时白板演示的时候，能加入类似与pdf，图片等文档类型的文件进行实时共享吗？

**Comment by imcuttle** [comment]
> pdf，图片等文档类型的文件进行实时共享

是可以的，可以在用户 a 上传某文件后，服务端广播消息，让其他客户端都知道用户 a 上传了文件，以达到实时共享的目的

**Comment by imcuttle** [comment]
太久没回复了，因此关闭 issue
